[package]
name = "westiny_client"
version = "0.1.0"
authors = ["Abel Suranyi"]
edition = "2018"

[dependencies]
westiny_common = { path = "../common" }
amethyst = "0.15.3"
amethyst_test = "0.15.3"
serde = "1.0.120"
anyhow = "1.0.38"
derive-new = "0.5.9"
log = "0.4.14"

[features]
default = ["vulkan", "tiles"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
tiles = ["amethyst/tiles"]
