[package]
name = "botanique-board"
version = "0.1.0"
authors = ["Domonkos Suranyi <domonkos.suranyi@protonmail.com>"]
edition = "2018"

[dependencies.piston]
version = "0.49.0"

[dependencies.piston2d-graphics]
version = "0.36.0"

[dependencies.pistoncore-glutin_window]
version = "0.63.0"

[dependencies.piston2d-opengl_graphics]
version = "0.72.0"
