[package]
name = "westiny"
version = "0.1.0"
authors = ["Domonkos Suranyi <domonkos.suranyi@protonmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.15.3"
amethyst_test = "0.15.3"
array-init = "1.0.0"
log = "0.4.11"
serde = { version = "1", features = ["derive"] }

[features]
default = ["vulkan", "tiles"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
tiles = ["amethyst/tiles"]
