[package]
name = "westiny"
version = "0.1.0"
authors = ["Domonkos Suranyi <domonkos.suranyi@protonmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.15.0"
mint = "0.5.5"
array-init = "0.1.1"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
