[package]
name = "westiny_server"
version = "0.1.0"
authors = ["Marton Suranyi"]
edition = "2018"

[dependencies]
westiny_common = { path = "../common"}
amethyst = "0.15.3"
amethyst_test = "0.15.3"
anyhow = "1.0.38"
thiserror = "1.0.23"
serde = "1.0.123"
derive-new = "0.5.8"
log = "0.4.14"
bincode = "1.3.1"
