[package]
name = "westiny_server"
version = "0.1.0"
authors = ["Marton Suranyi"]
edition = "2018"

[dependencies]
westiny_common = { path = "../common" }
bevy = "0.5.0"
bevy_asset_ron = "0.2.0"
anyhow = "1.0.38"
thiserror = "1.0.23"
serde = "1.0.123"
derive-new = "0.5.8"
log = "0.4.14"
pretty_env_logger = "0.4.0"
rand = "0.8.3"
blaminar = { git = "https://github.com/westinygame/blaminar" }

[dev-dependencies]
westiny_test = { path = "../test"}
